### ISSUE TITLE
Tries to rename folders

### ISSUE THREAD

**Issue by mybuntu-git2** [danboid/songrec-rename#7]
When running with -r with a bunch of subfolders, I get messages like
```
Error: UnrecognizedFormat
Renaming ABBA to -.ABBA
mv: invalid option -- '.'
Try 'mv --help' for more information.
```
Which do nothing in practice because of the failure, but should be prevented

**Comment by balucio** [comment]
Hi, when i first tried this application I had the same problem. After I relized that it works only on current directory. So if you want to rename music you must install `songrec-rename.sh` on `/usr/bin` or better `/usr/local/bin`, and then `cd` into your music directory. That's because it does not accept different folders.

**Comment by Passaita** [comment]
To solve this problem I modified the script and wrapped mv command with the folowing condition:
            		echo "Renaming $t to $subtitle - $title.$extension"
			if [ -f "$t" ]; then
				mv -n "$t" "$subtitle - $title.$extension"
			else
				echo "Skipping directory: $t"
			fi
			
Basically not touching anything if it's not a file.

**Comment by danboid** [comment]
Fixed. songrec-rename now only attempts to rename files.
